### ISSUE TITLE
Umlauts and other special characters

### ISSUE THREAD

**Issue by sgraf812** [reelsense/markdeep#1]
Hi,

I really love the simplicity of using this, so great work :)

Unfortunately, there is no easy way (& and hexcode isn't readable in non HTML) to insert umlauts and other special characters. I'd really appreciate handling this similar to what Markdown does, whatever that might be.

**Comment by reelsense** [comment]
Some how I never noticed your comment. I hope the newer releases have fixed your issue.
I do not maintain this software, I just loved the idea when I saw it posted here: [casual-effects.com/markdeep](http://casual-effects.com/markdeep/) and I wanted to maintain my own copy. Unfortunately @CasualEffects doesn't use github. So I just copy his code over when a new version comes out or I have time.

**Comment by sgraf812** [comment]
Hi,

nvm, I just used Markdown in the end.

**Comment by sualko** [comment]
@sgraf812 I guess you missed <code>&lt;meta charset="utf-8"></code> at the top of the document., because Umlaute are working just fine in my files.

**Comment by sgraf812** [comment]
Ah, thanks!
