### ISSUE TITLE
Unminified version available

### ISSUE THREAD

**Issue by cocoademon** [reelsense/markdeep#2]
Morgan McGuire has made the original unminified version available here:

https://casual-effects.com/markdeep/latest/markdeep.js

**Comment by reelsense** [comment]
oh, thank you!

**Comment by reelsense** [comment]
Done [37f5777](https://github.com/reelsense/markdeep/commit/37f5777ada5f4fb5a0fe9c8b90d7874c7028c640)

**Comment by reelsense** [comment]
As of 2016-08-31, 0.14 release date has not been finalized "`2016-08-?? Version 0.14: Robustness`".
